name: 'manifest-generator'
description: ''
author: ''
inputs:
  path: # change this
    required: true
    description: ''
    default: 'dist'
runs:
  using: 'node12'
  main: 'dist/manifest.js'
  # main: 'dist/index.js'
