name: 'manifest-generator'
description: ''
author: ''
inputs:
  path: # change this
    description: ''
    default: 'dist'
runs:
  using: 'composite' # 'node12'
  steps: 
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: Install dependencies
      run: yarn
    - name: Manifest
      run: npm run package.json && node scripts/manifest
      shell: bash
    - name: Build project
      run: yarn ci:build
