name: 'manifest-generator'
description: ''
author: ''
inputs:
  path: # change this
    required: true
    description: ''
    default: 'dist'
runs:
#   using: 'node12'
#   main: 'dist/manifest.js'
#   main: 'dist/index.js'
   name: Run Script
   shell: node12
   run: |
    const dirTree = require("directory-tree")
    const crypto = require('crypto')
    const fs = require('fs')
    let manifest = {
    version: require('../package.json').version,
    files: {}
    }
    dirTree("./${{ inputs.path }}", undefined, (item, path, stats) =>
    {
      let fname = item.path.replace(/^${{ inputs.path }}\//, '')
      let fcont = fs.readFileSync(item.path).toString('utf8')
      manifest.files[fname] = {
      "hash": crypto.createHash('sha256').update(fcont).digest('hex'),
      "size": stats.size
    }
    })
    fs.writeFileSync("./${{ inputs.path }}/manifest.json", JSON.stringify(manifest))
