name: 'manifest-generator'
description: ''
author: ''
inputs:
  path: # change this
    description: ''
    default: 'dist'
runs:
  using: 'composite' # 'node12'
  steps: 
    - name: Manifest
      run: browserify src/main.js -o bundle/script.js && node scripts/manifest
      shell: bash
