name: 'manifest-generator'
description: ''
author: 'wiz417'
inputs:
  path: # change this
    required: true
    description: 'directory for collecting filenames'
    default: 'dist'
runs:
  using: "composite"
  steps: 
    - name: Node
      run: |
        npm i;
        node dist/manifest.js
      shell: bash
