name: 'manifest-generator'
description: ''
author: ''
inputs:
  path: # change this
    description: ''
    default: 'dist'
runs:
  using: 'composite' # 'node12'
  steps: 
    - name: Archive
      run: node dist/index.js
      shell: bash
