name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: |
          npm install
          npm run build && npm run package

      - uses: Jnqa/manifest-generator@main
        with:
          path: 'dist'

      - name: Check
        run: |
          cat ./dist/manifest.json
