name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: bahmutov/npm-install@v1
      - run: npm ci
      - run: npm run build --if-present
      - run: npm install
      - name: npm install
        uses: jaid/action-npm-install@v1.2.1
      - uses: Jnqa/manifest-generator@main
        with:
          path: 'dist'
      - name: Check
        run: |
          cat ./dist/manifest.json
